// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiYQetZViww-HGD0I5Paq5I9P_htNlKdU',
    appId: '1:576608067709:web:8861f81117ac5df7849114',
    messagingSenderId: '576608067709',
    projectId: 'fir-tutorial-c7f6d',
    authDomain: 'fir-tutorial-c7f6d.firebaseapp.com',
    storageBucket: 'fir-tutorial-c7f6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ntcHQi0lRqyBaz8sgGd_0qirD2RYJYk',
    appId: '1:576608067709:android:7ff46928a07482d1849114',
    messagingSenderId: '576608067709',
    projectId: 'fir-tutorial-c7f6d',
    storageBucket: 'fir-tutorial-c7f6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUJd3MKzPDMt1RDh9suIIQbfxGNB_ryCg',
    appId: '1:576608067709:ios:265f3a2c8dd73002849114',
    messagingSenderId: '576608067709',
    projectId: 'fir-tutorial-c7f6d',
    storageBucket: 'fir-tutorial-c7f6d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUJd3MKzPDMt1RDh9suIIQbfxGNB_ryCg',
    appId: '1:576608067709:ios:265f3a2c8dd73002849114',
    messagingSenderId: '576608067709',
    projectId: 'fir-tutorial-c7f6d',
    storageBucket: 'fir-tutorial-c7f6d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiYQetZViww-HGD0I5Paq5I9P_htNlKdU',
    appId: '1:576608067709:web:e908b41c082c9d7c849114',
    messagingSenderId: '576608067709',
    projectId: 'fir-tutorial-c7f6d',
    authDomain: 'fir-tutorial-c7f6d.firebaseapp.com',
    storageBucket: 'fir-tutorial-c7f6d.firebasestorage.app',
  );
}
